# Generated by Django 4.2.5 on 2023-10-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True, max_length=512, null=True, unique=True
                    ),
                ),
                ("platform", models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                "db_table": "candidate",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="JoonggoData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=512, unique=True)),
                ("platform", models.CharField(blank=True, max_length=32, null=True)),
                ("issoldout", models.IntegerField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=128, null=True)),
                ("price", models.IntegerField(blank=True, null=True)),
                ("text", models.CharField(blank=True, max_length=4192, null=True)),
                ("mcnt", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "joonggo_data",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="JoonggoImg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=512)),
                ("img_url", models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                "db_table": "joonggo_img",
                "managed": False,
            },
        ),
    ]
